export const GET_UPCOMING = "GET_UPCOMING"
export const GET_POPULAR = "GET_POPULAR"
export const GET_TOPRATED = "GET_TOPRATED"
export const GET_NOWPLAYING = "GET_NOWPLAYING"

export const GET_MOVIEDETAILS = "GET_MOVIEDETAILS"
export const GET_MOVIECAST = "GET_MOVIECAST"

export const CLEAN_MOVIEDETAILS = "CLEAN_MOVIEDETAILS"
export const CLEAN_MOVIECAST = "CLEAN_MOVIECAST"